services:
  db:
    image: timescale/timescaledb:latest-pg18
    container_name: solarize-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-solarize}
      POSTGRES_USER: ${DB_USER:-pluto}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /var/lib/postgresql/tmp:size=100M
    security_opt:
      - no-new-privileges:true
    networks:
      - webnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solarize-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - webnet
  
  redis:
    image: redis:7-alpine
    container_name: solarize-redis
    restart: unless-stopped
    networks:
      - webnet

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solarize-celery
    command: celery -A data_factory.celery:app worker --loglevel=info
    networks:
      - webnet

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solarize-celery-beat
    command: celery -A data_factory.celery:app beat --loglevel=info
    networks:
      - webnet

  nginx:    
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: solarize-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/media:/app/media:ro
      - static_volume:/app/staticfiles:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
    tmpfs:
      - /var/cache/nginx:uid=101,gid=101,size=50M
      - /var/run:uid=101,gid=101,size=10M
    networks:
      - webnet

volumes:
  static_volume:
  postgres_data:
    driver: local

networks:
  webnet:
    driver: bridge