# Generated by Django 5.2.6 on 2025-11-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="job_title",
            field=models.CharField(default="Solar Enthusiast", max_length=50),
        ),
    ]
