DROP TABLE IF EXISTS irradiance_data CASCADE;
DROP TABLE IF EXISTS modelchain_results CASCADE;
DROP TABLE IF EXISTS ac_aoi CASCADE;
DROP TABLE IF EXISTS airmass CASCADE;
DROP TABLE IF EXISTS cell_temperature CASCADE;
DROP TABLE IF EXISTS dc_output CASCADE;
DROP TABLE IF EXISTS diode_params CASCADE;
DROP TABLE IF EXISTS total_irradiance CASCADE;
DROP TABLE IF EXISTS solar_position CASCADE;
DROP TABLE IF EXISTS weather CASCADE;


\i schema_setup.sql
